tap "atlassian/homebrew-acli"
tap "getsentry/tools"
tap "mongodb/brew"
brew "acli"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bash"
brew "bat"
brew "bc"
brew "berglas"
brew "ca-certificates"
brew "circleci"
brew "composer"
brew "coreutils"
brew "curl"
brew "difftastic"
brew "direnv"
brew "doggo"  # DNS client, nicer dig
brew "dos2unix"
brew "duckdb"
brew "editorconfig"
brew "elixir"
brew "erlang"
brew "eza"
brew "fd"
brew "felinks"  # required for VRSE
brew "gawk"
brew "gcc"
brew "gh"
brew "ghorg"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "go"
brew "helix"
brew "hyperfine"
brew "jless"
brew "jq"
brew "kubernetes-cli"
brew "lua"
brew "mactop"  # Apple Silicon system monitor
brew "luajit"
brew "micro"
brew "miller"
brew "mongocli"
brew "mongodb/brew/mongodb-database-tools"
brew "mycli"
# MySQL client only, pinned to 8.4 -- no server. The client supplies
# mysqldump, mysqladmin, mysqlcheck, mysqlimport, mysqlshow, mysqlbinlog and
# mysql_config, so nothing here needs the server package. Keg-only because it
# is a versioned formula, so .zprofile puts its bin on PATH explicitly.
brew "mysql-client@8.4"
brew "nano"
brew "ncurses"
brew "neovim"
brew "newrelic-cli"
brew "openblas"
brew "openjdk"
brew "openldap"
brew "openssh"
brew "p7zip"
brew "perl"
brew "php"
brew "rclone"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "rust"
brew "sentry"      # the `sentry` binary; distinct from sentry-cli
brew "sentry-cli"
brew "shellcheck"  # lints the scripts in this repo
brew "sqlite"
brew "sslscan"
brew "telnet"
brew "the_silver_searcher"
brew "uv"
brew "vim"
brew "websocat"
brew "wget"
brew "yamllint"
cask "1password-cli"
cask "gcloud-cli"
cask "ghostty"
cask "mongodb-compass"
